export const data = [{
    "first_name": "Tero",
    "last_name": "Hilden",
    "email": "tero.hilden@terveystalo.fi",
    "gender": "Mies",
    "city": "Liipola",
    "company": "terveystalo",
    "service": "Yleislääkäri",
    "date": "22/01/2023",	
    "time": "09:00",
    "lenght": "20 minuuttia",
    "price": "100 euroa",	
  }, 
  {
    "first_name": "Arttu",
    "last_name": "Heroja",
    "email": "arttu.heroja@herocare.com",
    "gender": "Mies",
    "city": "Espoo",
    "company": "herocare oy",
    "service": "Lastenlääkäri",
    "date": "30/01/2023",	
    "time": "10:00",
    "length": "30 minuuttia",
    "price": "100 euroa",     
  }, 
  {
    "first_name": "Helmi",
    "last_name": "Halonen",
    "email": "helmi.halonen@helmihoitaa.fi",
    "gender": "Nainen",
    "city": "Otaniemi",
    "company": "Helmi Hoitaa Oy",
    "service": "Gynekologi",
    "date": "04/02/2023",	
    "time": "11:00",
    "length": "30 minuuttia",
    "price": "200 euroa",
  }, {
    "first_name": "Lauri",
    "last_name": "Heroja",
    "email": "lauri@heroja.fi",
    "gender": "Mies",
    "city": "Lausanne",
    "company": "Heroja korjaa oy",
    "service": "Kardiologi",
    "date": "01/04/2023",	
    "time": "08:00",
    "length": "30 minuuttia",
    "price": "1100 euroa",
  }, {
    "first_name": "Maisa",
    "last_name": "Halonen",
    "email": "halonen@koirat.fi",
    "gender": "Nainen",
    "city": "Mikkeli",
    "company": "Hyvät tyypit oy",
    "service": "Unipalvelut",
    "date": "30/04/2023",	
    "time": "10:00",
    "length": "30 minuuttia",
    "price": "2200 euroa",
  }, {
    "first_name": "Kallu",
    "last_name": "Jokinen",
    "email": "jokinen@yahoo.com",
    "gender": "Mies",
    "city": "Tornio",
    "company": "VitaMed, LLC",
    "service": "Korvalääkäri",
    "date": "15/05/2023",	
    "time": "10:00",
    "length": "20 minuuttia",
    "price": "90 euroa",
  }, {
    "first_name": "Martta",
    "last_name": "Aaltonen",
    "email": "aaltonen@martta.fi",
    "gender": "Nainen",
    "city": "Helsinki",
    "company": "Martta oy",
    "service": "Silmälääkäri",
    "date": "04/05/2023",	
    "time": "10:00",
    "length": "10 minuuttia",
    "price": "100 euroa",
  }]